version: '3'

services: 
    rabbitmq:
        image: rabbitmq
        ports: 
            - 5672:5672
        network_mode: host

    flask-app:
        build: ./flask-app
        restart: on-failure
        ports: 
            - 5000:5000
        network_mode: host
        depends_on: 
            - rabbitmq
        
    prodcon:
        build: ./extractor-app
        network_mode: host
        restart: on-failure
        depends_on: 
            - rabbitmq